name: skysync
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  geocoding: ^3.0.0
  geolocator: ^13.0.1
  google_fonts: ^6.2.1
  http: ^1.2.2
  lottie: ^3.1.2
  url_launcher: ^6.3.0
  weather: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/Loading 2.json
    - assets/animations/Sunny.json
    - assets/animations/Cloudy.json
    - assets/animations/Storm.json
    - assets/animations/Thunder.json
    - assets/animations/Loading Animation.json
    - assets/animations/Fog.json
    - assets/animations/Smoke.json
    - assets/animations/About.json
